[functions.google-calendar-sync]
verify_jwt = true

[functions.google-oauth]
verify_jwt = true

[functions.form-submit]
verify_jwt = false

[functions.gmail-oauth]
verify_jwt = false

[functions.send-email]
verify_jwt = true
